name: nyc_311
version: 1.0.0
config-version: 2

profile: nyc_311

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  nyc_311:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: incremental
      +schema: marts
